#+title: Solana

[[file:../../../../homepage.org][Homepage]] / [[file:../../../../notes.org][Notes]] / [[file:../../../computer-science.org][Computer Science]] / [[file:../../blockchain.org][Blockchain]] / [[file:../cryptocurrencies.org][Cryptocurrencies]] / Solana

Block times of 400ms.
50,000 transactions per second.

Written in [[file:../../languages/rust.org][Rust]].

SPL tokens = equivalent to ERC20 tokens.

smart contracts = programs

* Wallet
** Using Ledger: https://solflare.com/dashboard

* Tools
- https://docs.solana.com/developing/clients/jsonrpc-api
- https://github.com/michaelhly/solana-py

** CLI
https://docs.solana.com/cli
*** Create a wallet
=solana-keygen new=
*** Check balance
=solana balance <PUBKEY>=
*** Send a token
=solana transfer --from <KEYPAIR> <RECIPIENT_ACCOUNT_ADDRESS> <AMOUNT> --fee-payer <KEYPAIR>=

** Anchor
https://github.com/project-serum/anchor
The "Truffle" of Solana

* Programs
- https://paulx.dev/blog/2021/01/14/programming-on-solana-an-introduction/
- https://hackmd.io/@ironaddicteddog/solana-starter-kit
- https://twitter.com/pencilflip/status/1451949960065335302
- https://jstarry.notion.site/Program-deploys-29780c48794c47308d5f138074dd9838

* Projects
[[https://github.com/project-serum/serum-dex][Serum]] declared itself defunct in Nov 2022 after the FTX/Alameda collapse
(FTX held its upgrade authority). Community-forked into OpenBook in 2023.

** Bonfida
Rebranded to Solana Name Service (SNS) in 2026.
https://docs.bonfida.com/#get-long-and-short-ratios

** Orca
https://www.orca.so/
Leading Solana DEX (Whirlpools), expanding into tokenized RWAs.

** Dashboards
*** Sonar.watch
Acquired by Jupiter in 2026, folded into Jupiter's portfolio-tracking feature.

** Raydium
AMM on Solana
Yield farming in a bunch of LPs there
https://raydium.io/farms

Made for Uniswap but should be the same for Raydium:
https://dailydefi.org/articles/lp-token-value-calculation/

** Mercurial => Meteora
Rebranded to Meteora in 2023 (clean break from FTX-linked MER token).
Now powers Jupiter Swap infra.
https://www.meteora.ag/

** Saber
https://saber.so/
AMM for stablecoins

** Symmetry
https://symmetry.fi/
"Create & invest in custom indices"

** Hedgehog
https://hedgehog.markets/
Relaunched in 2026 as a prediction market platform.

** Marinade.finance
https://marinade.finance/
Liquid staking protocol built on Solana blockchain.
Most-used Solana staking platform in 2026.

** Zeta Markets
https://zeta.markets/
Migrating to the "Bullet" network, ZEX token launch pending.

** Solend => Save
Rebranded to Save (save.finance) in July 2024.
Added SUSD stablecoin and SaveSOL LST.

** Drift Protocol
https://www.drift.trade/
Suffered a $286M exploit in April 2026 (durable-nonce attack).
Relaunch targeted Q3 2026 as a leaner perps-only venue.

** Jupiter
https://jup.ag/
Aggregator for best swap execution (1inch of Solana).
Dominant, ~95% of Solana DEX volume; acquired Sonar.watch, launched JupUSD stablecoin.

** Apricot
https://app.apricot.one/
Still live, retiring some features to focus dev effort; expanded to Aptos.

** Kamino
https://app.kamino.finance/
Lending platform. Largest lending protocol on Solana (~$3.2B TVL in 2026).
Absorbed Hubble Protocol's lending business (Hubble's USDH wound down 2024).

** List of new projects
https://solasystem.io/

** NFTs
*** SolanaMonkeyBusiness (SMB)
https://solanamonkey.business/
Still a blue-chip collection in 2026; SMB Gen3 in progress.
