[build]
  publish = "build/"

[build.processing.html]
  pretty_urls = true

[dev]
  autoLaunch = false

[[redirects]]
  from = "/homepage"
  to = "/"

[[redirects]]
  from = "/resume"
  to = "/about"
