#+title: Psychology

[[file:../homepage.org][Homepage]] / [[file:../notes.org][Notes]] / Psychology

* Big Five personality traits
https://en.wikipedia.org/wiki/Big_Five_personality_traits
** Openness to experience
Inventive/curious vs consistent/cautious
** Conscentiousness
Efficient/organized vs extravagant/careless
** Extraversion
Outgoing/energetic vs solitary/reserved
** Agreeableness
Friendly/compassionate vs critical/rational
** Neuroticism
Sensitive/nervous vs resilient/confident

* Emotional Intelligence
https://en.wikipedia.org/wiki/Emotional_intelligence
Capability for individuals to recognize their own emotions and those of others.

* Neuroticism
https://en.wikipedia.org/wiki/Neuroticism
Considered a fundamental personality trait.

* Learning How to Learn
** Focused vs Diffuse mode
Can't be in both modes at the same time.
Bain needs to go back in forth with both modes to learn effectively.

** Procrastination, Memory and Sleep
*** Procrastination
Everybody has issues with procrastination, but some people have more issues with procrastination than others.

When there's something you really don't want to do, you activate the area of your brain associated with pain (insular cortex).
Naturally, the brain tries to stop that negative stimulation by switching your attention to something else.
But soon after you start working, the neural discomfort disappears.

Unhappy feeling => Funnel attention to a more pleasant task => Feel happy (temporarily).

*** Practice Makes Permanent
Important to practice, especially with abstract concepts.
A little every day > All at once.

*** Memory
**** Working memory
Prefrontal cortex.
Used to believe it could "hold" ~7 chunks of memory, now believed it can only holds about 4 chunks of memory.
Have to keep repeating so it says in working memory.

**** Long term memory
Distributed over a large area in the brain.
Takes time and practice to go from working memory to long term memory.
Spaced repetition!

*** Sleep
Being awake creates toxic products in the brain.
The brain gets rid of it by sleeping. "Washes the toxins out".

Important part of the memory and learning process.
Brain tidies up ideas and concepts.
Erases less important parts and strengthen ides you need or want to remember.

Dreaming about what you're studying can substantially enhance your ability to understand.

** Interview with Dr. Terrence Sejnowski
Firm believer of learning by doing.
You learn more by active engagement than passive listening.

Out jogging/walking, it's nice for diffuse mode of thinking and get new ideas.
Hard to remember them along the way though, need to write them down.

Multi-tasking => Context switching.
Can't actually do two things at the same time.
Need to be better at context switching to be able to switch between tasks faster and more easily.

An enriched environment or exercise can create new neurons.
Being in an environment where other people are creatives can enhance your creativity.

Success: passion + persistence.
Not letting go.

** Chunking
*** What is a chunk?
Chunks are pieces of information, bound together through meaning or use.
A network of neurons that are used to firing together, so you can think a thought or perform an action smoothly and effectively.
Path to expertise is built little by little, small chunks becoming larger.
Practice and repetition.
Chunking helps the brain run more efficiently.

*** How to form a chunk?
"You're creating little neural mini chunks that you can then gradually knit together into larger neural chunks."
"Later, you can knit those larger chunks into still larger and more complex chunks that you can draw up in an instant in reaction say to a slight shift and twist in the soccer ball that's coming your way."
"The best chunks are the ones that are so well ingrained that you don't even have to consciously think about connecting the neural pattern together."

- Focus undivided attention to the information you'd like to chunk.
  No TV, clock, notifications...
  New neural patterns and connecting them with preexisting patterns that are spread through many other areas of the brain.

- Understand the basic idea you're trying to chunk.
  Understanding is a like a superglue that holds all the underlying ideas together.
  Really important to try to do it / solve it yourself.
  Only doing it yourself creates the neural pattern that underlie true mastery.

- Gain context.
  So you know how but also when to use this chunk.
  Chunks can be tool, but you need to know when to use those tools.
  Bottom-up learning: chunking.
  Top-down learning: big picture.
  Context is where bottom-up and top-down meet.

*** Illusions of Competence
**** Importance of Recall
In the same amount of time, by simply practicing and recalling the material, students learned far more and at a much deeper level.
When we retrieve knowledge, the retrieval process itself, enhances deep learning (and helps us forming chunks).
Recall > passive re-reading.
Re-reading is only effective if time passes between re-reading, then it becomes similar to spaced repitition.

**** Illusions of Competence
- Seeing a solution at the end, being confident that you understand, could reproduce it => big mistake
- Highlighting or underlining a text => a mistake as well, but writing notes in the margin is effective
- Just spending time with the material, or thinking you've learnt while you have the material (or Google) in front of your eyes is wrong.

**** Mini-testing & making mistakes
Mistakes are very valuable in self-tests, allows to know what to focus on, what not to reproduce.

**** Change of environment
Try to recalling while in a different (physical) environment.
The brain might associate some cues with the physical environment where we initially learnt the material.

** What Motivates You?
It is hard to learn when you're not into it.
But if it's something you're really interested in, learning is easy.

*** Neuromodulators
"Neuromodulators are chemicals that influence how a neuron responds to other neurons."
http://BrainFacts.org

**** Acetylcholine
Important for focused learning (paying close attention).

**** Dopamine
Controls motivation.
Reward learning.
Released when we receive an unexpected reward.

"Dopamine is in the business of predicting future rewards and not just the immediate reward. This can motivate you to do something that may not be rewarding right now, but will lead to a much better reward in the future."
"Addictive drugs artificially increase dopamine activity and fool your brain into thinking that something wonderful has just happened. In fact, just the opposite has just happened. This leads to craving and dependence which can hijack your free will and can motivate actions that are harmful too."
"Loss of dopamine neurons leads to a lack of motivation and something called anhedonia, which is a loss of interest in things that once gave you pleasure."
"Severe loss of dopamine neurons causes resting tremor, slowness, rigidity, this is called Parkinson's disease."

**** Serotonine
Strongly affects your social life.
In monkeys, alpha males who lead the group have the highest activity of serotonine, while the lowest ranking ones have the lowest levels of serotonine activity.
Prozac raises the level of serotonine activity.
Also closely linked to risk-taking behaviour.
Higher risk in lower serotonin monkeys.
"Inmates in jail for violent crimes have some of the lowest levels of serotonin activity in society."

** The Value of a Library of Chunks
Sequential problem solving: focused mode of learning.
Holistic/global problem solving: diffuse mode of learning.
Intuitive insights aren't always correct.
Law of Serendipity: Lady Luck favours the one who tries.

** Overlearning, Einstellung and Interleaving
*** Overlearning
Can be useful when automaticity is important.
Executing a perfect serve in tennis, a perfect piano concerto or to practic public speaking.
But most times, it's not beneficial at all.
*Interleaving* is better.
Can bring an illusion of competence if you keep rehearsing the "easy" stuff.
*Deliberate practice*: focusing on purpose on what's difficult.

*** Einstellung
Einstellung = mindset.
When you already have an idea/thought and it prevents you from finding an even better idea/solution.
Like installing a roadblock because of the way you were *initially* looking at something.

*** Interleaving
*Interleaving*: mix studying with practice of problems of different types.
Don't jump into the water without knowing how to swim.
Learning a new subject is also about learning what's the best "chunk" to use for a particular situation.

Important to know when to use a particular technique.
Allows you to learn more "deeply".
Adds flexibility and creativity to the mind.

One issue:
"Jack of all trades, master of none"
When you work on building links between two disciplines, you don't have as much knowledge as someone who specializes
in that one discipline only. (like me with marketing & software development :))

Most paradigm shifts occur by either:
- young people
- people who were originally trained in another discipline

** Interview with Dr. Norman Fortenberry - Learning at MIT
Writing down material from a Powerpoint allows to internalize the material.

Tutoring/teaching is an excellent way to learn.
Even bouncing ideas with other students is great ("hey this is what I think I know" etc...).

** Interview with Scott Young
Analogy/metaphors really help.

MOOC are great, but might not be the best for advanced subjects.
For that, MIT OpenCourseWare (OCW) is amazing: https://ocw.mit.edu/.

** Procrastination
Willpower is hard to come by.
Unhappy feeling => Funnel attention to a more pleasant task => Feel happy (temporarily).
Shares features with addiction.

In tiny doses, arsenic doesn't seem harmful. Can even build up an immunity.
Can allow you to take larger doses and look healthy even though the poison is ravaging your organs.

Procrastinators put off that one little thing, do it again and again, look healthy, but the long term effects are not so good.

*** Habits
Chunking is related to habits. Habit is an energy saver for us, allows us to free our mind for other types of activities.

Habits have four parts:
1. The cue: the trigger that launch you into "zombie mode". Can be helpful or harmful.
2. The routine: /zombie mode/, the routine habitual response your brain is used to falling into when it receives the cue.
3. The reward: why procrastination is so pleasant. Finding ways to reward good study habits is important for escaping procrastination.
4. The belief: habits have a power because you have a belief in them.

*** Process vs Product
Completely normal to feel a few negative feelings about beginning a learning/working session.
Even when it's something you usually like.
It's how you handle those feelings that matters.

Non-procrastinators put their feelings aside.

Focus on *process*, not *product*.
*Process* means the flow of time and the habits and actions associated with that flow of time.
*Product* is an outcome (ex: something you need to finish).
The product is what triggers the pain that causes you to procrastinate.
To avoid procrastination, you want to avoid focusing on product, instead your focus should be on building processes.
The small chunks of time you need over days or even weeks to do what you want to accomplish.

When a distraction arises, just let if flow by.
Setting yourself up so distractions are minimal is also a very good idea.

*** Overriding Habits
The trick to overriding a habit is to change your reaction to a cue.
The only place you need to apply willpower is to change your reaction to the cue.
Because procrastination is an automatic habit, you're often unaware that you've begun to procrastinate.

By using the 4 habits mentioned earlier:
1. The cue: you can prevent the most damaging cues by shutting off your cell phone or keeping yourself away from the Internet and other distractions.
2. The routine: the key to rewiring is to have a plan. Developing a new ritual can be helpful. Just keep at it and adjust the plan if necessary.
3. The reward: why are you procrastinating? Allow yourself to a reward after achieving a goal.
4. The belief: hang out with classmates (or "MOOCmates"). Developing culture with like-minded friends can help us remember the values that we tend to forget.

*** Juggling Life and Learning
Once a week, write down a brief list of tasks in a planner journal.
Each day, write a list of tasks you can reasonably work on or accomplish.
Write to write this daily task list the evening before.
Research has shown it helps the subconscious to grapple with the tasks on the list.

Without a task list, tasks take up valuable mental real estate.
When you have a task list, it frees working memory for problem solving.

Mixing other tasks with your learning/working seems to make everything more enjoyable and keeps you from prolonged, unhealthy bouts of sitting.
Implement/plan for a finish time, like 17:00.
Always try to squeeze break/leisure time.

Try to work on the most important or most unpleasant task as soon as you wake up.

** Memory
Outstanding visual and spatial memory.
Needed for our ancestors to remember the path to get back home or where to get food.

To go from working memory to long term memory, idea must be memorable and repeated.
"People often underestimate the benefits of spaced repetition when learning."

*** What is Long Term Memory?
Hippocampus is important for learning and memory of facts and events.
Without the hippocampus, it is impossible to store new memories in the cortex (memory consolidation).
After a concussion, you can have amnesia, but it usually resolves.
It is possible to implant false memories.

*** Meaningful Groups & Memory Palace Technique
Easier to remember numbers by associating them with memorable events.
Memory Palace Technique: imagine/visualize a place that you know well (your home...) and visualize what you need to remember inside that place.
Memory tricks can speed up the memorization process.

** Change Your Thoughts, Change Your Life
Approaching material with a goal of learning it on your own can give you a unique path to mastery.
Not matter how good your teachers and textbooks are, it's only when you sneak off and look at other books or videos that you begin to see what you learn through a single teacher or book is a *partial* version of the full 3D reality of the subjects, which has links to other fascinating topics.
Taking responsibility for your own learning is one of the most important things you can do.

If you do well in your studies, the people around you can feel threatened.
The greater your achievements, the more other people will sometimes attack and demean your efforts.
Tune people out if you discover their interests lie in undercutting you.
Take pride in who you are, especially in the qualities that make you different and use them as a secret talisman for success.
Use your natural contrariness to defy the always present prejudices from others about what you can accomplish.

** Hard Start - Jump to Easy Test Technique
Go overall the entire material.
Begin by the hardest part, then quickly switch to the easier problems.
This will trigger diffuse mode and help solve the harder problems.

* CBT
https://www.thegreatcoursesplus.com/cognitive-behavioral-therapy-for-daily-life

* Nonviolent Communication (NVC)
https://en.wikipedia.org/wiki/Nonviolent_Communication

* I no longer aspire to have a career.
https://www.youtube.com/watch?v=nKFypHcnGu4

* Growth mindset
- Abilities and intelligence are not fixed traits and can be developed through dedicated effort and continuous learning
- Viewing challenges as opportunities for growth
- Putting in effort is crucial for mastering new skills

* Cognitive Biases
https://www.shortcogs.com/
